<?php
$order_id = $block->getData('order_id');
$customParameter = $block->getDetail();
?>
<main id="site-content" role="main">
   <div class="cr-plugin-copy">
      <p>Copied</p>
   </div>
   <article class="post-8 page type-page status-publish hentry" id="post-8">
      <input type="hidden" id="address" value="<?php echo $customParameter['order_address'];?>">
      <input type="hidden" id="order_id" value="<?php echo $customParameter['order_id'];?>">
      <input type="hidden" id="coin" value="<?php echo $customParameter['coin'];?>">
      <input type="hidden" id="expire_on">
      <input type="hidden" id="current">
      <input type="hidden" id="imageBase" value="<?php echo $this->getViewFileUrl('Coinremitter_Checkout::images'); ?>">
      <div class="post-inner thin ">
         <div class="entry-content">
            <div class="cr-plugin-main-box clearfix">
               <div class="cr-plugin-left">
                  <div class="cr-plugin-shipping cr-plugin-shadow cr-plugin-mr-top clearfix">
                     <div class="cr-plugin-shipping-address">
                        <h3 class="cr-plugin-title">Billing Address</h3>
                        <p>
                           <?php echo $customParameter['billingFirstName'];?> <?php echo $customParameter['billingLastName'];?> <br>
                           <?php echo implode(', ', $customParameter['billingStreet']);?> <br>
                           <?php echo $customParameter['billingCity'];?> - <?php echo $customParameter['billingPostcode'];?> <br>
                           <?php echo $customParameter['billingState_name'];?> <?php echo $customParameter['billingCountry_name'];?><br>
                           <?php echo $customParameter['billingTelephone'];?>
                        </p>
                     </div>
                     <?php if($customParameter['show_shipping']){?>
                        <div class="cr-plugin-billing-address">
                           <h3 class="cr-plugin-title">Shipping Address</h3>
                           <p>
                              <?php echo $customParameter['shippingFirstName'];?> <?php echo $customParameter['shippingLastName'];?> <br>
                              <?php echo implode(', ', $customParameter['shippingStreet']);?> <br>
                              <?php echo $customParameter['shippingCity'];?> - <?php echo $customParameter['shippingPostcode'];?> <br>
                              <?php echo $customParameter['shippingState_name'];?> <?php echo $customParameter['shippingCountry_name'];?><br>
                              <?php echo $customParameter['shippingTelephone'];?>
                           </p>
                        </div>
                     <?php } ?>
                  </div>
                  <div class="cr-plugin-cart-summary cr-plugin-shadow cr-plugin-mr-top">
                     <h3 class="cr-plugin-title">Cart Summary</h3>
                     <div class="cr-plugin-cart-table">
                        <div class="cr-plugin-cart-table-box">
                           <table>
                              <thead>
                                 <tr>
                                    <th>Product Info</th>
                                    <th style="text-align: center;">Quantity</th>
                                    <th style="text-align: right;">Price</th>
                                 </tr>
                              </thead>
                              <tbody>
                                 <?php
                                 foreach ($customParameter['products'] as $product) {
                                    ?>
                                    <tr>
                                       <td style="width: 300px;">
                                          <div class="cr-plugin-cart-img">
                                             <img src="<?php echo $product['productImage'];?>" align="">
                                          </div>
                                          <div class="cr-plugin-cart-des">
                                             <p><?php echo $product['productName'];?> <?php echo $product['productOptions'];?></p>
                                          </div>
                                       </td>
                                       <td style="text-align: center;">
                                          <span><?php echo $product['productQty'];?></span>
                                       </td>
                                       <td style="text-align: right;">
                                          <span><?php echo $customParameter['orderCurrencySymbol'];?> <?php echo $product['productPrice'];?></span>
                                       </td>
                                    </tr>
                                    <?php
                                 }
                                 ?>
                              </tbody>
                           </table>
                        </div>
                     </div>
                     <div class="cr-plugin-payment-detail">
                        <h3 class="cr-plugin-title">Payment Details</h3>
                        <ul>
                           <li>Total <span><?php echo $customParameter['orderCurrencySymbol'];?> <?php echo $customParameter['subTotal'];?></span></li>
                           <li>Shipping  Fee <span><?php echo $customParameter['orderCurrencySymbol'];?> <?php echo $customParameter['shippingAmount'];?></span></li>
                           <li>Total Taxes <span><?php echo $customParameter['orderCurrencySymbol'];?> <?php echo $customParameter['taxAmount'];?></span></li>
                        </ul>
                        <ul class="cr-plugin-payment-grand">
                           <li>Grand Total <span><?php echo $customParameter['orderCurrencySymbol'];?> <?php echo $customParameter['grandTotal'];?></span></li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="cr-plugin-right">
                  <div class="cr-plugin-billing-main cr-plugin-shadow">
                     <h3 class="cr-plugin-title">Billing Address</h3>
                     <div class="cr-plugin-timer" id="timerStatus"></div>
                     <div class="cr-plugin-billing-box">
                        <div class="cr-plugin-billing-code">
                           <img class="copyToClipboard" data-copy-detail="<?php echo $customParameter['order_address'];?>" src="<?php echo $customParameter['qr_code'];?>" title="click to copy" align="">
                        </div>
                        <div class="cr-plugin-billing-amount">
                           <ul>
                              <li>
                                 <span>Address</span>
                                 <p class="copyToClipboard" title="click to copy" data-copy-detail="<?php echo $customParameter['order_address'];?>"><?php echo $customParameter['order_address'];?> <img src="<?php echo $this->getViewFileUrl('Coinremitter_Checkout::images/copy.png'); ?>"></p>
                              </li>
                              <li>
                                 <span>Amount</span>
                                 <p class="copyToClipboard" title="click to copy" data-copy-detail="<?php echo $customParameter['totalAmount'];?>"><?php echo $customParameter['totalAmount'];?> <?php echo $customParameter['coin'];?></p>
                              </li>
                           </ul>
                        </div>
                     </div>
                  </div>
                  <div class="cr-plugin-payment-history cr-plugin-shadow cr-plugin-mr-top">
                     <h3 class="cr-plugin-title">Payment  History</h3>
                     <div class="cr-plugin-timer" id="paymentStatus"></div>
                     <div class="cr-plugin-history-list" id="cr-plugin-history-list">
                        <div class="cr-plugin-history-box">
                           <div class="cr-plugin-history">
                              
                           </div>
                        </div>
                     </div>
                     <div class="cr-plugin-history-footer">
                        <ul class="clearfix">
                           <li>Paid <span id="paid-amt">0.00000000 <?php echo $customParameter['coin'];?></span></li>
                           <li>Pending <span id="pending-amt"><?php echo $customParameter['totalAmount'];?> <?php echo $customParameter['coin'];?></span></li>
                        </ul>
                     </div>
                  </div>
                  <div class="cr-plugin-brand">
                     <span>Secured by</span>
                     <a href="https://coinremitter.com" target="_blank">
                        <img src="<?php echo $this->getViewFileUrl('Coinremitter_Checkout::images/logo.png'); ?>">
                     </a>
                  </div>
               </div>
            </div>
         </div>
         <!-- .entry-content -->
      </div>
      <!-- .post-inner -->
   </article>
   <!-- .post -->
</main>