<?php
$order_id = $block->getData('order_id');
$customParameter = $block->getDetail();
?>
<main id="site-content" role="main">
   <div class="cr-plugin-copy">
      <p>Copied</p>
   </div>
   <article class="post-8 page type-page status-publish hentry" id="post-8">
      <input type="hidden" id="address" value="<?= $escaper->escapeHtmlAttr($customParameter['order_address']) ?>">
      <input type="hidden" id="order_id" value="<?= $escaper->escapeHtmlAttr($customParameter['order_id']) ?>">
      <input type="hidden" id="coin" value="<?= $escaper->escapeHtmlAttr($customParameter['coin']) ?>">
      <input type="hidden" id="expire_on">
      <input type="hidden" id="current">
      <input type="hidden" id="imageBase" value="<?= $escaper->escapeUrl($block->getViewFileUrl('Coinremitter_Checkout::images')) ?>">
      <div class="post-inner thin ">
         <div class="entry-content">
            <div class="cr-plugin-main-box clearfix">
               <div class="cr-plugin-left">
                  <div class="cr-plugin-shipping cr-plugin-shadow cr-plugin-mr-top clearfix">
                     <div class="cr-plugin-shipping-address">
                        <h3 class="cr-plugin-title">Billing Address</h3>
                        <p>
                           <?= $escaper->escapeHtml($customParameter['billingFirstName']) ?> 
                           <?= $escaper->escapeHtml($customParameter['billingLastName']) ?> <br>
                           <?= $escaper->escapeHtml(implode(', ', $customParameter['billingStreet'])) ?> <br>
                           <?= $escaper->escapeHtml($customParameter['billingCity']) ?> - 
                           <?= $escaper->escapeHtml($customParameter['billingPostcode']) ?> <br>
                           <?= $escaper->escapeHtml($customParameter['billingState_name']) ?> 
                           <?= $escaper->escapeHtml($customParameter['billingCountry_name']) ?><br>
                           <?= $escaper->escapeHtml($customParameter['billingTelephone']) ?>
                        </p>
                     </div>
                     <?php if ($customParameter['show_shipping']) { ?>
                        <div class="cr-plugin-billing-address">
                           <h3 class="cr-plugin-title">Shipping Address</h3>
                           <p>
                              <?= $escaper->escapeHtml($customParameter['shippingFirstName']) ?> 
                              <?= $escaper->escapeHtml($customParameter['shippingLastName']) ?> <br>
                              <?= $escaper->escapeHtml(implode(', ', $customParameter['shippingStreet'])) ?> <br>
                              <?= $escaper->escapeHtml($customParameter['shippingCity']) ?> - 
                              <?= $escaper->escapeHtml($customParameter['shippingPostcode']) ?> <br>
                              <?= $escaper->escapeHtml($customParameter['shippingState_name']) ?> 
                              <?= $escaper->escapeHtml($customParameter['shippingCountry_name']) ?><br>
                              <?= $escaper->escapeHtml($customParameter['shippingTelephone']) ?>
                           </p>
                        </div>
                     <?php } ?>
                  </div>
                  <div class="cr-plugin-cart-summary cr-plugin-shadow cr-plugin-mr-top">
                     <h3 class="cr-plugin-title">Cart Summary</h3>
                     <div class="cr-plugin-cart-table">
                        <div class="cr-plugin-cart-table-box">
                           <table>
                              <thead>
                                 <tr>
                                    <th>Product Info</th>
                                    <th style="text-align: center;">Quantity</th>
                                    <th style="text-align: right;">Price</th>
                                 </tr>
                              </thead>
                              <tbody>
                                 <?php
                                    foreach ($customParameter['products'] as $product) {
                                        ?>
                                    <tr>
                                       <td style="width: 300px;">
                                          <div class="cr-plugin-cart-img">
                                             <img src="<?= $escaper->escapeUrl($product['productImage']) ?>" align="">
                                          </div>
                                          <div class="cr-plugin-cart-des">
                                             <p><?= $escaper->escapeHtml($product['productName']) ?> 
                                             <?= $escaper->escapeHtml($product['productOptions']) ?></p>
                                          </div>
                                       </td>
                                       <td style="text-align: center;">
                                          <span><?= $escaper->escapeHtml($product['productQty']) ?></span>
                                       </td>
                                       <td style="text-align: right;">
                                          <span><?= $escaper->escapeHtml($customParameter['orderCurrencySymbol']) ?> 
                                          <?= $escaper->escapeHtml($product['productPrice']) ?></span>
                                       </td>
                                    </tr>
                                        <?php
                                    }
                                    ?>
                              </tbody>
                           </table>
                        </div>
                     </div>
                     <div class="cr-plugin-payment-detail">
                        <h3 class="cr-plugin-title">Payment Details</h3>
                        <ul>
                           <li>Total 
                           <span><?= $escaper->escapeHtml($customParameter['orderCurrencySymbol']) ?> 
                           <?= $escaper->escapeHtml($customParameter['subTotal']) ?></span></li>
                           <li>Shipping  Fee 
                           <span><?= $escaper->escapeHtml($customParameter['orderCurrencySymbol']) ?> 
                           <?= $escaper->escapeHtml($customParameter['shippingAmount']) ?></span></li>
                           <?php if (isset($customParameter['order_discount'])) { ?>
                              <li>Discount 
                              <span><?= $escaper->escapeHtml($customParameter['orderCurrencySymbol']) ?> 
                                <?= $escaper->escapeHtml($customParameter['order_discount']) ?></span></li>
                           <?php } ?>
                           <li>Total Taxes 
                           <span><?= $escaper->escapeHtml($customParameter['orderCurrencySymbol']) ?> 
                           <?= $escaper->escapeHtml($customParameter['taxAmount']) ?></span></li>
                        </ul>
                        <ul class="cr-plugin-payment-grand">
                           <li>Grand Total 
                           <span><?= $escaper->escapeHtml($customParameter['orderCurrencySymbol']) ?> 
                           <?= $escaper->escapeHtml($customParameter['grandTotal']) ?></span></li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="cr-plugin-right">
                  <div class="cr-plugin-billing-main cr-plugin-shadow">
                     <h3 class="cr-plugin-title">Billing Address</h3>
                     <div class="cr-plugin-timer" id="timerStatus"></div>
                     <div class="cr-plugin-billing-box">
                        <div class="cr-plugin-billing-code">
                           <img class="copyToClipboard" 
                           data-copy-detail="<?= $escaper->escapeHtmlAttr($customParameter['order_address']) ?>" 
                           src="<?= $escaper->escapeUrl($customParameter['qr_code']) ?>" 
                           title="click to copy" align="">
                        </div>
                        <div class="cr-plugin-billing-amount">
                           <ul>
                              <li>
                                 <span>Address</span>
                                 <p class="copyToClipboard" title="click to copy" 
                                 data-copy-detail="<?= $escaper->escapeHtmlAttr($customParameter['order_address']) ?>">
                                 <?= $escaper->escapeHtml($customParameter['order_address']) ?> 
                                 <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Coinremitter_Checkout::images/copy.png')) ?>">
                                 </p>
                              </li>
                              <li>
                                 <span>Amount</span>
                                 <p class="copyToClipboard" title="click to copy" 
                                 data-copy-detail="<?= $escaper->escapeHtmlAttr($customParameter['totalAmount']) ?>">
                                 <?= $escaper->escapeHtml($customParameter['totalAmount']) ?> 
                                 <?= $escaper->escapeHtml($customParameter['coin']) ?></p>
                              </li>
                           </ul>
                        </div>
                     </div>
                  </div>
                  <div class="cr-plugin-payment-history cr-plugin-shadow cr-plugin-mr-top">
                     <h3 class="cr-plugin-title">Payment  History</h3>
                     <div class="cr-plugin-timer" id="paymentStatus"></div>
                     <div class="cr-plugin-history-list" id="cr-plugin-history-list">
                        <div class="cr-plugin-history-box">
                           <div class="cr-plugin-history">
                              
                           </div>
                        </div>
                     </div>
                     <div class="cr-plugin-history-footer">
                        <ul class="clearfix">
                           <li>Paid <span id="paid-amt">0.00000000 <?= $escaper->escapeHtml($customParameter['coin']) ?></span></li>
                           <li>Pending 
                           <span id="pending-amt"><?= $escaper->escapeHtml($customParameter['totalAmount']) ?> 
                           <?= $escaper->escapeHtml($customParameter['coin']) ?></span></li>
                        </ul>
                     </div>
                  </div>
                  <div class="cr-plugin-brand">
                     <span>Secured by</span>
                     <a href="https://coinremitter.com" target="_blank">
                        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Coinremitter_Checkout::images/logo.svg')) ?>">
                     </a>
                  </div>
               </div>
            </div>
         </div>
         <!-- .entry-content -->
      </div>
      <!-- .post-inner -->
   </article>
   <!-- .post -->
</main>
